name: Setup testing environment
description: Set up the poetry environment
runs:
  using: "composite"
  steps:
    - run: pipx install poetry==1.8.3
      shell: bash
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: "poetry"
    - run: poetry install
      shell: bash
